"""CCSDS CDM/ODM standards — Conjunction & Orbit Data Messages.

Generate and parse standard CCSDS messages so OrbitWarden speaks the operational
community's language:
  · CDM (Conjunction Data Message) — CCSDS 508.0-B-1
  · ODM / OMM (Orbit Mean-Elements Message) — CCSDS 502.0-B-2

A CDM generator turns our scored events into something an operator could feed
into existing SSA tooling; an OMM generator publishes our orbit in standard form.
Both support the KVN (keyword=value) format used operationally.

References:
  CCSDS 508.0-B-1, "Conjunction Data Message" (Blue Book)
  CCSDS 502.0-B-2, "Orbit Data Messages" (Blue Book)
"""

from __future__ import annotations

from datetime import datetime, timezone

from engine.models import ScoredConjunction, TLEData


def _fmt_epoch(dt: datetime) -> str:
    """CCSDS epoch format: YYYY-MM-DDTHH:MM:SS.ffffff (UTC)."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")


def generate_cdm(
    event: ScoredConjunction,
    primary: TLEData,
    secondary: TLEData | None = None,
    cdm_id: str | None = None,
    created: datetime | None = None,
) -> str:
    """Generate a CCSDS CDM (KVN format) for a scored conjunction.

    Produces a standards-compliant Conjunction Data Message that an operator
    could ingest into existing SSA tooling. Fields follow CCSDS 508.0-B-1.

    Args:
        event: the scored conjunction.
        primary: the primary satellite TLE (for name/id).
        secondary: the secondary object TLE (optional, for name/id).
        cdm_id: message identifier (defaults to a generated one).
        created: message creation time (defaults to now).

    Returns:
        CDM as a KVN-format string.
    """
    if created is None:
        created = datetime.now(timezone.utc)
    if cdm_id is None:
        cdm_id = f"OW_{primary.norad_id}_{event.secondary_norad}_{event.tca.strftime('%Y%m%d%H%M%S')}"

    sec_name = secondary.name if secondary else event.secondary_name
    sec_id = secondary.norad_id if secondary else event.secondary_norad
    sec_type = event.secondary_type or "UNKNOWN"

    lines = [
        "CCSDS_CDM_VERS = 1.0",
        f"CREATION_DATE = {_fmt_epoch(created)}",
        f"ORIGINATOR = ORBITWARDEN",
        "",
        f"MESSAGE_ID = {cdm_id}",
        f"MESSAGE_FOR = OPERATOR",
        f"EMERGENCY_REPORTABLE = {'YES' if event.risk_score >= 60 else 'NO'}",
        "",
        "TCA = " + _fmt_epoch(event.tca),
        f"MISS_DISTANCE = {event.miss_distance_km * 1000:.3f}",  # meters
        f"RELATIVE_SPEED = {event.relative_velocity_kms:.6f}",  # km/s
        "",
        f"RELATIVE_POSITION_R = {event.miss_r_km * 1000:.3f}",  # meters
        f"RELATIVE_POSITION_T = {event.miss_s_km * 1000:.3f}",
        f"RELATIVE_POSITION_N = {event.miss_w_km * 1000:.3f}",
        "",
        f"COLLISION_PROBABILITY = {event.pc:.6e}",
        "COLLISION_PROBABILITY_METHOD = ALFRIEND_AKELLA_2D_FIXED_COVARIANCE",
        "",
        f"OBJECT1 = {primary.name}",
        f"OBJECT1_ID = {primary.norad_id}",
        "OBJECT1_OBJECT_TYPE = PAYLOAD",
        "",
        f"OBJECT2 = {sec_name}",
        f"OBJECT2_ID = {sec_id}",
        f"OBJECT2_OBJECT_TYPE = {sec_type}",
        "",
        "COMMENT = Generated by OrbitWarden; covariance is a documented fixed",
        "COMMENT = RSW estimate (see docs/ADVANCED_ASTRODYNAMICS.md). Human approval required.",
    ]
    return "\n".join(lines)


def parse_cdm_kvn(text: str) -> dict:
    """Parse a CCSDS CDM (KVN format) into a dict of fields.

    Handles the common CDM fields; unknown keys are preserved. Useful for
    ingesting external CDMs for validation or interoperability.
    """
    fields: dict = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("COMMENT"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        fields[key.strip()] = value.strip()
    return fields


def generate_omm(tle: TLEData, originator: str = "ORBITWARDEN") -> str:
    """Generate a CCSDS OMM (Orbit Mean-Elements Message, KVN) from a TLE.

    Publishes the orbit in standard mean-element form (CCSDS 502.0-B-2), the
    modern successor to the TLE for sharing orbit data.

    Args:
        tle: the TLE to convert.
        originator: message originator.

    Returns:
        OMM as a KVN-format string.
    """
    # Parse TLE line 2 elements.
    line2 = tle.line2
    inclination = float(line2[8:16])
    raan = float(line2[17:25])
    eccentricity = float("0." + line2[26:33])
    arg_perigee = float(line2[34:42])
    mean_anomaly = float(line2[43:51])
    mean_motion = float(line2[52:63])  # rev/day

    # Semi-major axis from mean motion: n = sqrt(mu/a^3); n in rad/s.
    import math

    mu = 398600.4418
    n_rad_s = mean_motion * 2 * math.pi /86400.0
    semi_major = (mu / n_rad_s**2) ** (1.0 / 3.0)

    lines = [
        "CCSDS_OMM_VERS = 2.0",
        f"CREATION_DATE = {_fmt_epoch(datetime.now(timezone.utc))}",
        f"ORIGINATOR = {originator}",
        "",
        f"OBJECT_NAME = {tle.name}",
        f"OBJECT_ID = {tle.norad_id}",
        "CENTER_NAME = EARTH",
        "REF_FRAME = TEME",
        "TIME_SYSTEM = UTC",
        "",
        f"MEAN_ELEMENT_THEORY = SGP4",
        f"EPOCH = {_fmt_epoch(tle.epoch)}",
        f"MEAN_MOTION = {mean_motion:.8f}",  # rev/day
        f"ECCENTRICITY = {eccentricity:.7f}",
        f"INCLINATION = {inclination:.4f}",  # deg
        f"RA_OF_ASC_NODE = {raan:.4f}",  # deg
        f"ARG_OF_PERICENTER = {arg_perigee:.4f}",  # deg
        f"MEAN_ANOMALY = {mean_anomaly:.4f}",  # deg
        f"SEMI_MAJOR_AXIS = {semi_major:.3f}",  # km
        "",
        f"NORAD_CAT_ID = {tle.norad_id}",
        "COMMENT = Converted from TLE by OrbitWarden.",
    ]
    return "\n".join(lines)
